# Generated by Django 4.1.3 on 2022-11-23 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngestNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingest_date', models.DateTimeField(auto_now_add=True)),
                ('filename', models.FilePathField(path='/data', recursive=True)),
                ('status', models.TextField(default='PENDING', editable=False)),
            ],
            options={
                'ordering': ['-ingest_date'],
            },
        ),
    ]
