# Generated by Django 4.1 on 2022-08-10 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingest',
            name='status',
            field=models.TextField(default='PENDING'),
        ),
    ]
