# Generated by Django 4.1 on 2022-08-10 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0002_ingest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingest',
            name='status',
            field=models.TextField(default='PENDING', editable=False),
        ),
    ]
