"""
Django settings for lick_searchable_archive project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
from os import environ
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent / "lick_searchable_archive"

UNIT_TEST_DIR = environ['UNIT_TEST_DIR']

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&rfumrv32o4gj&)s+y@7sjqu=-%ncsd5a8(-(!2myfxv=f7)et'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['testserver']


# Application definition

INSTALLED_APPS = [
#    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
#    'django.contrib.sessions',
#    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
#    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
#    'django.contrib.auth.middleware.AuthenticationMiddleware',
#    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'lick_searchable_archive.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'lick_searchable_archive.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': f'{UNIT_TEST_DIR}/db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LOGGING = {
    'version':1,
    'disable_existing_loggers': False,
    'handlers': {
        'django_log': {
            'class': 'logging.FileHandler',
            'filename': f'{UNIT_TEST_DIR}/django_log.txt',   
            'level': 'DEBUG',         
            'formatter': 'archive_log_formatter',
        },
    },
    'formatters': {
        'archive_log_formatter': {
            # log format used through out the lick searchable archive.
            '()': 'lick_archive.script_utils.get_std_log_formatter',
            'log_pid': True,  # Log the gunicorn worker pid
        },
    },
    'loggers': {
        '': {
            'level': 'DEBUG',         
            'handlers': ['django_log']
        },
    },
}
# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

#STATIC_ROOT = '{{ venv_root }}/python{{ python_version }}/site-packages/lick_searchable_archive/static_files'
STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Celery configuration
#CELERY_BROKER_URL = '{{ redis_url }}'


# Lick Archive settings
LICK_ARCHIVE_API_VERSION = '1'

LICK_ARCHIVE_ROOT_DIR = f'/data'

LICK_ARCHIVE_INSTRUMENT_DIRS = ['AO', 'shane']

LICK_ARCHIVE_ALLOW_INGEST = True

LICK_ARCHIVE_QUERY_USER  = 'user'
LICK_ARCHIVE_INGEST_USER = 'user'
LICK_ARCHIVE_DB          = f'{UNIT_TEST_DIR}/test_metadta_db.sqlite3'
LICK_ARCHIVE_HEADER_URL_FORMAT = "http://testserver/files/{}/header"