- name: Local init
  hosts: 127.0.0.1
  connection: local
  roles:
    - local_init

- name: Deploys lick searchable archive to a single node
  hosts: backend
  roles:
    - common
    - common_sw
    - admin_tools
