- name: DB Server playbook
  hosts: appservers
  tasks:
      - name: Copy db scripts
        ansible.builtin.copy: 
          src: db
          dest: .
      - name: Install python packages
        ansible.builtin.pip:
          name: sqlalchemy, tenacity, astropy, alembic
          state: present
        become: yes


