- name: Local init
  hosts: 127.0.0.1
  connection: local
  roles:
    - local_init

- name: DB Server playbook
  hosts: backend
  roles:
    - common
    - admin_tools
    - database
  handlers:
  - name: Restart gunicorn
    ansible.builtin.systemd:
      name: gunicorn.service
      enabled: yes
      daemon_reload: no
      state: restarted
    become: yes
    listen: 
      - "restart web services"
      - "common config changed"
