- name: Local init
  hosts: 127.0.0.1
  connection: local
  roles:
    - local_init

- name: Install Django Applications
  hosts: backend
  roles:
    - base
    - django_apps

  handlers:
    - name: Retart celery
      ansible.builtin.systemd:
        name: celery.service
        enabled: yes
        daemon_reload: yes
        state: restarted
      become: yes
      listen:
        - "restart web services"
        - "common config changed"
    - name: Restart gunicorn
      ansible.builtin.systemd:
        name: gunicorn.service
        enabled: yes
        daemon_reload: no
        state: restarted
      become: yes
      listen: 
        - "restart web services"
        - "common config changed"

