- name: Local init
  hosts: 127.0.0.1
  connection: local
  roles:
    - local_init

- name: Deploys lick searchable archive frontend
  hosts: frontend
  roles:
    - common
    - django_site
    - django_apps
    - webserver
  handlers:
    - name: Restart gunicorn
      ansible.builtin.systemd:
        name: gunicorn.service
        enabled: yes
        daemon_reload: no
        state: restarted
      become: yes
      listen: 
        - "restart web services"
        - "common config changed"
    - name: Restart Apache2
      ansible.builtin.systemd:
        name: apache2
        enabled: yes
        daemon_reload: yes
        state: restarted
      become: yes
      listen:
        - "restart web server"
        - "common config changed"
