- name: Local init
  hosts: 127.0.0.1
  connection: local
  roles:
    - local_init

- name: Ingest Watchdog Remote Deploy Playbook
  hosts: watchdog
  roles:
    - common
    - ingest_watchdog

  handlers:
    - name: Restart Ingest Service
      ansible.builtin.systemd:
        name: ingest_watchdog.service
        enabled: yes
        daemon_reload: yes
        state: restarted
      become: yes
      listen: 
        - "restart watchdog"
        - "common config changed"
