- name: Deploys lick searchable archive to a single node
  hosts: dbservers:appservers:ingest_servers:watchdog
  vars:
    remote_watchdog: False
  roles:
    - common
    - database
    - ingest_watchdog
    - django_apps