- name: Deploys lick searchable archive to a single node
  hosts: dbservers:appservers:ingest_servers:watchdog
  roles:
    - common
    - database
    - role: ingest_watchdog
      vars:
        remote_watchdog: False
    - role: django_apps